version: "3.3"

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    restart: on-failure

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - /home/decastromonteiro/docker-volumes/static:/home/app/web/static_root
      - /home/decastromonteiro/docker-volumes/media:/home/app/web/media_root
    ports:
      - "8000:8000"
    env_file:
      - ./env/web.dev
      - ./env/twitter
    restart: always
    depends_on:
      - db

  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A thepacketwizards worker -l INFO
    env_file:
      - ./env/web.dev
      - ./env/twitter
    restart: always
    depends_on:
      - web
      - rabbitmq

  db:
    image: postgres:12.0-alpine
    volumes:
      - /home/decastromonteiro/docker-volumes/database:/var/lib/postgresql/data/
    env_file:
      - ./env/db.prod
    restart: always
