version: "3.3"

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    restart: on-failure

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn thepacketwizards.wsgi:application --bind [::]:8000
    volumes:
      - /home/decastromonteiro/docker-volumes/static:/home/app/web/static_root
      - /home/decastromonteiro/docker-volumes/media:/home/app/web/media_root
    expose:
      - 8000
    env_file:
      - ./env/web.prod
      - ./env/twitter
    restart: on-failure
    depends_on:
      - db

  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A thepacketwizards worker -l INFO
    env_file:
      - ./env/web.prod
      - ./env/twitter
    restart: on-failure
    depends_on:
      - web
      - rabbitmq

  db:
    image: postgres:12.0-alpine
    volumes:
      - /home/decastromonteiro/docker-volumes/database:/var/lib/postgresql/data/
    env_file:
      - ./env/db.prod
    restart: on-failure

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - /home/decastromonteiro/docker-volumes/static:/home/app/web/static_root
      - /home/decastromonteiro/docker-volumes/media:/home/app/web/media_root
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /home/decastromonteiro/letsencrypt/live/thepacketwizards.com/fullchain.pem:/etc/letsencrypt/live/thepacketwizards.com/fullchain.pem
      - /home/decastromonteiro/letsencrypt/live/thepacketwizards.com/privkey.pem:/etc/letsencrypt/live/thepacketwizards.com/privkey.pem
      - /home/decastromonteiro/letsencrypt/letsencrypt-site:/data/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    depends_on:
      - web
