# Generated by Django 3.0.3 on 2020-03-03 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191107_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='next_post',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='previous_post',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogseries',
            name='description',
            field=models.TextField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Author'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
