# Generated by Django 3.0.3 on 2020-04-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200405_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail_alt_text',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
