# Generated by Django 3.1.1 on 2020-10-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201003_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterpost',
            name='task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
